[[rules]]
  id = "generic-api-key"
  [rules.allowlist]
    commits = [
      # Allowlist placeholder API key in transitions.rs
      "12faf7bd764685b4327fa213c8e47092723f9f38",
      "3a98baf1cf77f725249192f08248d9d15a993a6e",
      "d506e938a126525e8afbde878203df1c9308ff53",
      "c8efac81365648b0236d691a2fc622ba0d516f0c"
    ]

[[rules]]
  id = "apollo-graphos-api-key"
  [rules.allowlist]
    commits = [
      "c8efac81365648b0236d691a2fc622ba0d516f0c"
    ]
    paths = [
      "src/command/init/tests/template_consistency_test.rs",
      "src/command/init/tests/mcp_flow_integration_test.rs",
      "src/command/init/tests/mcp_next_steps_test.rs",
      "src/command/init/tests/template_hydration_tests.rs",
      "src/command/init/tests/mcp_prompting_tests.rs"
    ]