//! `plugin-versions.lock`: the record of which plugin releases are installed
//! at one level, and which version request produced each of them.
//!
//! It is TOML, where the manifest beside it is YAML: people write the
//! manifest, but only Rover writes this file, and every value in it has to
//! read back exactly as it was written.
//!
//! Rover writes this file and people commit it, so its serialization is
//! deterministic: entries in [`PluginName::ALL`] order and fields in a fixed
//! order, so that rewriting a lockfile with the same contents changes nothing
//! a diff would show.

use std::{collections::BTreeMap, fmt};

use semver::Version;
use serde::{Deserialize, Deserializer, Serialize, Serializer, de};
use serde_with::{DisplayFromStr, serde_as};

use super::version::{PluginName, VersionRequest};

/// A lockfile's file name, next to the manifest of the level it records.
pub const LOCKFILE: &str = "plugin-versions.lock";

/// The one lockfile format this version of Rover reads and writes.
const FORMAT_VERSION: u64 = 1;

/// The comment every lockfile Rover writes starts with.
const HEADER: &str = "# This file is generated by Rover. It is not intended for manual editing.\n";

/// The contents of one `plugin-versions.lock`: at most one locked release per
/// plugin.
#[derive(Debug, Default, Clone, PartialEq, Eq)]
pub struct PluginLockfile(BTreeMap<PluginName, LockedPlugin>);

/// One plugin's entry in a lockfile. Every value is a TOML string, parsed
/// with the same grammar a user's version request is.
#[serde_as]
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct LockedPlugin {
    #[serde_as(as = "DisplayFromStr")]
    pub name: PluginName,
    /// The version request that produced this entry, which says whether
    /// [`Self::resolved`] came from resolving a floating alias.
    #[serde_as(as = "DisplayFromStr")]
    pub requested: VersionRequest,
    /// The exact release installed.
    #[serde_as(as = "DisplayFromStr")]
    pub resolved: Version,
    /// The verified digest of the installed artifact, as `sha256:<hex>`.
    /// Absent for a release locked before the registry published checksums.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub checksum: Option<String>,
}

impl PluginLockfile {
    pub fn get(&self, plugin: PluginName) -> Option<&LockedPlugin> {
        self.0.get(&plugin)
    }

    /// Every entry, in the order [`PluginName::ALL`] names the plugins.
    pub fn iter(&self) -> impl Iterator<Item = &LockedPlugin> {
        self.0.values()
    }

    pub fn is_empty(&self) -> bool {
        self.0.is_empty()
    }

    /// The file's contents, exactly as Rover writes them to disk.
    pub fn render(&self) -> String {
        let body =
            toml::to_string(self).expect("every field of a lockfile serializes as a TOML string");
        format!("{HEADER}{body}")
    }
}

/// A later entry for a plugin replaces an earlier one.
impl FromIterator<LockedPlugin> for PluginLockfile {
    fn from_iter<I: IntoIterator<Item = LockedPlugin>>(entries: I) -> Self {
        Self(
            entries
                .into_iter()
                .map(|entry| (entry.name, entry))
                .collect(),
        )
    }
}

/// The on-disk shape: the format version, then the entries as a list.
#[derive(Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct Format<T> {
    version: u64,
    #[serde(default = "Vec::new")]
    plugins: Vec<T>,
}

impl Serialize for PluginLockfile {
    fn serialize<S: Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        Format {
            version: FORMAT_VERSION,
            plugins: self.iter().collect(),
        }
        .serialize(serializer)
    }
}

impl<'de> Deserialize<'de> for PluginLockfile {
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let format = Format::<LockedPlugin>::deserialize(deserializer)?;
        if format.version != FORMAT_VERSION {
            return Err(de::Error::custom(format!(
                "unsupported lockfile version `{}`",
                format.version
            )));
        }

        let mut entries = BTreeMap::new();
        for entry in format.plugins {
            if !entry.is_consistent() {
                return Err(de::Error::custom(Inconsistent(&entry)));
            }
            if entries.contains_key(&entry.name) {
                return Err(de::Error::custom(format!(
                    "`{}` is locked more than once",
                    entry.name
                )));
            }
            entries.insert(entry.name, entry);
        }

        Ok(Self(entries))
    }
}

impl LockedPlugin {
    /// Whether [`Self::resolved`] is a release [`Self::requested`] could have
    /// produced.
    fn is_consistent(&self) -> bool {
        match self.requested.exact() {
            Some(exact) => *exact == self.resolved,
            None => self
                .requested
                .major()
                .is_none_or(|major| major == self.resolved.major),
        }
    }
}

struct Inconsistent<'a>(&'a LockedPlugin);

impl fmt::Display for Inconsistent<'_> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let LockedPlugin {
            name,
            requested,
            resolved,
            ..
        } = self.0;
        write!(
            f,
            "`{name}` is locked at `{resolved}`, which the request `{requested}` could not have resolved to"
        )
    }
}

#[cfg(test)]
mod tests {
    use indoc::indoc;
    use rstest::rstest;
    use speculoos::prelude::*;

    use super::*;

    fn locked(name: PluginName, requested: VersionRequest, resolved: Version) -> LockedPlugin {
        LockedPlugin {
            name,
            requested,
            resolved,
            checksum: None,
        }
    }

    #[rstest]
    fn a_lockfile_renders_in_plugin_order_whatever_order_it_was_built_in() {
        let lockfile: PluginLockfile = [
            locked(
                PluginName::ApolloMcpServer,
                VersionRequest::Latest,
                Version::new(1, 0, 0),
            ),
            LockedPlugin {
                checksum: Some("sha256:0a1b".to_string()),
                ..locked(
                    PluginName::Supergraph,
                    VersionRequest::Major(2),
                    Version::new(2, 9, 3),
                )
            },
            locked(
                PluginName::Router,
                VersionRequest::Exact(Version::new(2, 1, 0)),
                Version::new(2, 1, 0),
            ),
        ]
        .into_iter()
        .collect();

        assert_that!(lockfile.render().as_str()).is_equal_to(indoc! {r#"
            # This file is generated by Rover. It is not intended for manual editing.
            version = 1

            [[plugins]]
            name = "supergraph"
            requested = "2"
            resolved = "2.9.3"
            checksum = "sha256:0a1b"

            [[plugins]]
            name = "router"
            requested = "=2.1.0"
            resolved = "2.1.0"

            [[plugins]]
            name = "apollo-mcp-server"
            requested = "latest"
            resolved = "1.0.0"
        "#});
    }

    #[rstest]
    fn an_empty_lockfile_still_names_its_format() {
        assert_that!(PluginLockfile::default().render().as_str()).is_equal_to(indoc! {r#"
            # This file is generated by Rover. It is not intended for manual editing.
            version = 1
            plugins = []
        "#});
    }

    #[rstest]
    #[case::every_plugin(PluginLockfile::from_iter([
        locked(PluginName::Supergraph, VersionRequest::Major(2), Version::new(2, 9, 3)),
        locked(PluginName::Router, VersionRequest::Latest, Version::new(2, 1, 0)),
        locked(
            PluginName::ApolloMcpServer,
            VersionRequest::Exact(Version::new(1, 0, 0)),
            Version::new(1, 0, 0),
        ),
    ]))]
    #[case::a_checksum(PluginLockfile::from_iter([LockedPlugin {
        checksum: Some("sha256:0a1b".to_string()),
        ..locked(PluginName::Router, VersionRequest::Major(2), Version::new(2, 1, 0))
    }]))]
    #[case::a_prerelease(PluginLockfile::from_iter([locked(
        PluginName::Router,
        VersionRequest::Exact(Version::parse("2.1.0-rc.1").unwrap()),
        Version::parse("2.1.0-rc.1").unwrap(),
    )]))]
    #[case::nothing(PluginLockfile::default())]
    fn a_rendered_lockfile_reads_back_unchanged(#[case] lockfile: PluginLockfile) {
        assert_that!(toml::from_str::<PluginLockfile>(&lockfile.render()))
            .is_ok()
            .is_equal_to(lockfile);
    }

    #[rstest]
    #[case::inline_tables(
        indoc! {r#"
            version = 1
            plugins = [{ name = "supergraph", requested = "2", resolved = "2.9.3" }]
        "#},
        locked(PluginName::Supergraph, VersionRequest::Major(2), Version::new(2, 9, 3))
    )]
    #[case::a_legacy_spelling(
        indoc! {r#"
            version = 1

            [[plugins]]
            name = "supergraph"
            requested = "latest-2"
            resolved = "2.9.3"
        "#},
        locked(PluginName::Supergraph, VersionRequest::Major(2), Version::new(2, 9, 3))
    )]
    fn a_hand_edited_entry_still_reads(#[case] input: &str, #[case] expected: LockedPlugin) {
        assert_that!(toml::from_str::<PluginLockfile>(input))
            .is_ok()
            .is_equal_to(PluginLockfile::from_iter([expected]));
    }

    /// The whole message, less the location and source excerpt `toml`
    /// prints above it, which say where rather than what.
    fn problem(input: &str) -> String {
        let error = toml::from_str::<PluginLockfile>(input).expect_err("should not parse");
        error.message().to_string()
    }

    #[rstest]
    #[case::a_plugin_locked_twice(
        indoc! {r#"
            version = 1
            plugins = [
              { name = "router", requested = "2", resolved = "2.1.0" },
              { name = "router", requested = "2", resolved = "2.2.0" },
            ]
        "#},
        "`router` is locked more than once"
    )]
    #[case::an_exact_request_locked_at_another_release(
        indoc! {r#"
            version = 1
            plugins = [{ name = "router", requested = "=2.1.0", resolved = "2.2.0" }]
        "#},
        "`router` is locked at `2.2.0`, which the request `=2.1.0` could not have resolved to"
    )]
    #[case::a_major_locked_outside_it(
        indoc! {r#"
            version = 1
            plugins = [{ name = "supergraph", requested = "2", resolved = "3.0.0" }]
        "#},
        "`supergraph` is locked at `3.0.0`, which the request `2` could not have resolved to"
    )]
    #[case::an_unknown_plugin(
        indoc! {r#"
            version = 1
            plugins = [{ name = "apollo-router", requested = "2", resolved = "2.1.0" }]
        "#},
        "`apollo-router` is not a Rover plugin. Valid plugins are `supergraph`, `router`, and \
         `apollo-mcp-server`."
    )]
    #[case::a_request_that_is_not_a_string(
        indoc! {r#"
            version = 1
            plugins = [{ name = "router", requested = 2, resolved = "2.1.0" }]
        "#},
        "invalid type: integer `2`, expected a string"
    )]
    #[case::a_resolved_version_that_is_not_exact(
        indoc! {r#"
            version = 1
            plugins = [{ name = "router", requested = "2", resolved = "2" }]
        "#},
        "unexpected end of input while parsing major version number"
    )]
    #[case::an_unknown_entry_field(
        indoc! {r#"
            version = 1
            plugins = [{ name = "router", requested = "2", resolved = "2.1.0", sha = "abc" }]
        "#},
        "unknown field `sha`, expected one of `name`, `requested`, `resolved`, `checksum`"
    )]
    #[case::a_missing_version("plugins = []\n", "missing field `version`")]
    #[case::another_format_version(
        "version = 2\nplugins = []\n",
        "unsupported lockfile version `2`"
    )]
    fn an_unusable_lockfile_is_rejected_saying_why(#[case] input: &str, #[case] expected: &str) {
        assert_that!(problem(input).as_str()).is_equal_to(expected);
    }

    /// A problem with one value names where in the file it is.
    #[rstest]
    fn a_rejected_value_is_located() {
        let error = toml::from_str::<PluginLockfile>(indoc! {r#"
            version = 1

            [[plugins]]
            name = "router"
            requested = "2"
            resolved = "2.x"
        "#})
        .expect_err("should not parse");

        assert_that!(error.to_string().as_str()).is_equal_to(indoc! {r#"
            TOML parse error at line 6, column 12
              |
            6 | resolved = "2.x"
              |            ^^^^^
            unexpected character 'x' while parsing minor version number
        "#});
    }
}
