[alias]
xtask = "run --package xtask --"
rover = "run --package rover --"
install-rover = "run --release --package rover -- install --force"
test-next = "test --all-features -- --nocapture"
build-next = "build --features composition-js,dev-next"