//! A bare `rover plugin install` through the real binary: it installs exactly
//! the releases the lockfile at the level it targets records, without asking
//! the registry to resolve anything (FR36), and fails rather than install some
//! other release when it can't install the locked one. A declaration the
//! lockfile doesn't record yet is resolved and recorded, alone (FR16).

use std::{fs, process::Command};

use assert_cmd::cargo::cargo_bin;
use camino::Utf8Path;
use httpmock::{Method, MockServer};
use rstest::rstest;
use serde_json::{Value, json};
use speculoos::prelude::*;

use super::spellings::supergraph_tarball;
use crate::support::plugin_levels::{Level, TwoLevels, two_levels};

const LOCKFILE: &str = "plugin-versions.lock";

/// A lockfile recording `supergraph`'s floating `2` as v2.9.3.
const LOCKED: &str = "# This file is generated by Rover. It is not intended for manual editing.\n\
                      version = 1\n\n[[plugins]]\nname = \"supergraph\"\nrequested = \"2\"\n\
                      resolved = \"2.9.3\"\n";

/// How the registry answers a request for a `supergraph` artifact.
#[derive(Clone, Copy)]
enum Artifact {
    Served,
    Withdrawn,
}

/// What a run of Rover did: its exit code and JSON envelope, how many times
/// it asked the registry to resolve a version, and how many artifacts it
/// downloaded.
type Run = (Option<i32>, Value, usize, usize);

/// Run `rover <args>` at `levels`, against a registry that resolves every
/// floating alias to v2.9.5, newer than anything locked, so a run that
/// resolved one would install that instead.
fn rover(levels: &TwoLevels, args: &[&str], artifact: Artifact) -> Run {
    let server = MockServer::start();
    let resolutions = server.mock(|when, then| {
        when.method(Method::HEAD);
        then.status(302).header("X-Version", "v2.9.5");
    });
    let downloads = server.mock(|when, then| {
        when.method(Method::GET).path_includes("/tar/supergraph/");
        match artifact {
            Artifact::Served => then.status(200).body(supergraph_tarball(b"#!/bin/sh\n")),
            Artifact::Withdrawn => then.status(410),
        };
    });
    let mut command = Command::new(cargo_bin("rover"));
    levels.apply(&mut command);
    let output = command
        .args(args)
        .args(["--download-host", &format!("http://{}", server.address())])
        .args(["--client-timeout", "1", "--skip-update-check"])
        .args(["--telemetry-disabled", "--format", "json"])
        .env("NO_COLOR", "1")
        // binstall reads this directly, and it would move the global root.
        .env_remove("APOLLO_NODE_MODULES_BIN_DIR")
        .env_remove("APOLLO_ROVER_NO_DOWNLOAD")
        .env_remove("APOLLO_ROVER_GLOBAL")
        .output()
        .unwrap();
    let stderr = String::from_utf8_lossy(&output.stderr).to_string();
    let json = serde_json::from_slice(&output.stdout)
        .unwrap_or_else(|err| panic!("stdout isn't JSON ({err})\nstderr: {stderr}"));
    (
        output.status.code(),
        json,
        resolutions.calls(),
        downloads.calls(),
    )
}

fn rover_dir(levels: &TwoLevels, level: Level) -> camino::Utf8PathBuf {
    match level {
        Level::Global => levels.global.rover_dir(),
        Level::Project => levels.project.rover_dir(),
    }
}

fn lockfile(dir: &Utf8Path) -> Option<String> {
    fs::read_to_string(dir.join(LOCKFILE)).ok()
}

/// The names of the files in `bin_dir`, which need not exist.
fn installed(bin_dir: &Utf8Path) -> Vec<String> {
    let mut names: Vec<String> = fs::read_dir(bin_dir)
        .into_iter()
        .flatten()
        .map(|entry| entry.unwrap().file_name().to_string_lossy().to_string())
        .collect();
    names.sort();
    names
}

/// `supergraph` v2.9.3 as `data.plugins` reports it downloaded at `level`.
fn downloaded(levels: &TwoLevels, level: Level) -> Value {
    let path = levels
        .bin_dir(level)
        .join(format!("supergraph-v2.9.3{}", std::env::consts::EXE_SUFFIX));
    json!({
        "name": "supergraph",
        "version": "2.9.3",
        "source": "downloaded",
        "level": match level {
            Level::Global => "global",
            Level::Project => "project",
        },
        "path": path.as_str(),
    })
}

#[rstest]
#[case::the_project_with_its_manifest(Level::Project, true, &["plugin", "install"])]
#[case::the_project_with_only_a_lockfile(Level::Project, false, &["plugin", "install"])]
#[case::the_global_level(Level::Global, true, &["plugin", "install", "--global"])]
fn a_bare_install_installs_the_locked_release_without_resolving_it(
    two_levels: TwoLevels,
    #[case] level: Level,
    #[case] with_manifest: bool,
    #[case] args: &[&str],
) {
    let dir = rover_dir(&two_levels, level);
    fs::write(dir.join(LOCKFILE), LOCKED).unwrap();
    if with_manifest {
        fs::write(dir.join("rover.yaml"), "plugins:\n  supergraph: \"2\"\n").unwrap();
    }

    let (code, json, resolutions, downloads) = rover(&two_levels, args, Artifact::Served);

    assert_that!((code, &json["data"]["plugins"], resolutions, downloads))
        .named(&json.to_string())
        .is_equal_to((Some(0), &json!([downloaded(&two_levels, level)]), 0, 1));
    assert_that!(lockfile(&dir)).is_equal_to(Some(LOCKED.to_string()));
    let other = match level {
        Level::Global => Level::Project,
        Level::Project => Level::Global,
    };
    assert_that!(installed(&two_levels.bin_dir(other))).is_equal_to(Vec::<String>::new());
}

#[rstest]
fn a_locked_release_the_registry_withdrew_fails_rather_than_install_another(two_levels: TwoLevels) {
    fs::write(two_levels.project.rover_dir().join(LOCKFILE), LOCKED).unwrap();

    let (code, json, resolutions, downloads) =
        rover(&two_levels, &["plugin", "install"], Artifact::Withdrawn);

    // The one resolution is the registry naming its newest 2.x for the
    // suggestion, after the locked release has failed.
    assert_that!((code, &json["error"], resolutions, downloads)).is_equal_to((
        Some(1),
        &json!({
            "message": "The `supergraph` plugin v2.9.3, locked in `plugin-versions.lock`, is no \
                        longer available from the plugin registry. The newest available 2.x is \
                        v2.9.5.",
            "code": "E051",
            "plugin": "supergraph",
            "requested_version": "=2.9.3",
        }),
        1,
        1,
    ));
    assert_that!(installed(&two_levels.project.bin_dir())).is_equal_to(Vec::<String>::new());
}

#[rstest]
fn a_locked_release_the_manifest_no_longer_allows_fails_before_any_download(two_levels: TwoLevels) {
    let dir = two_levels.project.rover_dir();
    fs::write(dir.join(LOCKFILE), LOCKED).unwrap();
    fs::write(
        dir.join("rover.yaml"),
        "plugins:\n  supergraph: \"=2.9.4\"\n",
    )
    .unwrap();

    let (code, json, resolutions, downloads) =
        rover(&two_levels, &["plugin", "install"], Artifact::Served);

    assert_that!((code, &json["error"], resolutions, downloads)).is_equal_to((
        Some(1),
        &json!({
            "message": format!(
                "The plugin lockfile is out of date with `{}`: `supergraph` is declared as \
                 `=2.9.4` but locked at `2.9.3`.",
                dir.join("rover.yaml")
            ),
            "code": "E052",
            "plugin": "supergraph",
            "requested_version": "=2.9.4",
        }),
        0,
        0,
    ));
    assert_that!(lockfile(&dir)).is_equal_to(Some(LOCKED.to_string()));
}

/// The router stays at its locked release, installed already, while the
/// `supergraph` declaration the lockfile lacks resolves to the newest 2.x and
/// is the only entry added.
#[rstest]
fn a_declaration_the_lockfile_lacks_is_resolved_and_recorded_alone(two_levels: TwoLevels) {
    let dir = two_levels.project.rover_dir();
    let router_entry = "[[plugins]]\nname = \"router\"\nrequested = \"latest\"\nresolved = \
                        \"2.1.0\"\nchecksum = \"sha256:0a1b\"\n";
    fs::write(dir.join(LOCKFILE), format!("version = 1\n\n{router_entry}")).unwrap();
    fs::write(
        dir.join("rover.yaml"),
        "plugins:\n  supergraph: \"2\"\n  router: latest\n",
    )
    .unwrap();
    let router = two_levels.seed_plugin(Level::Project, "router", "2.1.0");

    let (code, json, resolutions, downloads) =
        rover(&two_levels, &["plugin", "install"], Artifact::Served);

    let supergraph = two_levels
        .project
        .bin_dir()
        .join(format!("supergraph-v2.9.5{}", std::env::consts::EXE_SUFFIX));
    assert_that!((code, &json["data"]["plugins"], resolutions, downloads))
        .named(&json.to_string())
        .is_equal_to((
            Some(0),
            &json!([
                {
                    "name": "supergraph",
                    "version": "2.9.5",
                    "source": "downloaded",
                    "level": "project",
                    "path": supergraph.as_str(),
                },
                {
                    "name": "router",
                    "version": "2.1.0",
                    "source": "installed",
                    "level": "project",
                    "path": router.as_str(),
                },
            ]),
            1,
            1,
        ));
    assert_that!(lockfile(&dir)).is_equal_to(Some(format!(
        "# This file is generated by Rover. It is not intended for manual editing.\n\
         version = 1\n\n[[plugins]]\nname = \"supergraph\"\nrequested = \"2\"\n\
         resolved = \"2.9.5\"\n\n{router_entry}"
    )));
}

#[rstest]
fn a_bare_install_with_nothing_in_scope_asks_for_a_plugin(two_levels: TwoLevels) {
    let dir = two_levels.project.rover_dir();

    let (code, json, resolutions, downloads) =
        rover(&two_levels, &["plugin", "install"], Artifact::Served);

    assert_that!((code, &json["error"], resolutions, downloads)).is_equal_to((
        Some(1),
        &json!({
            "message": format!(
                "No plugin was named, and there's no `{}` or `{}` to install from.",
                dir.join("rover.yaml"),
                dir.join(LOCKFILE)
            ),
            "code": null,
        }),
        0,
        0,
    ));
}
