//! Which level's install root `rover plugin install` installs into, through
//! the real binary: the project in scope by default, and the global level
//! when there is no project.

use std::{fs, process::Command};

use assert_cmd::cargo::cargo_bin;
use camino::Utf8Path;
use httpmock::{Method, MockServer};
use rstest::rstest;
use serde_json::{Value, json};
use speculoos::prelude::*;

use super::spellings::supergraph_tarball;
use crate::support::plugin_levels::{Level, TwoLevels, two_levels};

const HEADER: &str = "# This file is generated by Rover. It is not intended for manual editing.\n";

/// What `supergraph@=2.9.3` records in a lockfile.
const LOCKED: &str = "version = 1\n\n[[plugins]]\nname = \"supergraph\"\nrequested = \"=2.9.3\"\n\
                      resolved = \"2.9.3\"\n";

/// Run `rover <args>` at `levels`, against a registry serving `supergraph`
/// v2.9.3, returning the exit code and the JSON envelope.
fn rover(levels: &TwoLevels, args: &[&str], env: &[(&str, &str)]) -> (Option<i32>, Value) {
    let server = MockServer::start();
    server.mock(|when, then| {
        when.method(Method::GET).path_includes("/tar/supergraph/");
        then.status(200).body(supergraph_tarball(b"#!/bin/sh\n"));
    });
    let mut command = Command::new(cargo_bin("rover"));
    levels.apply(&mut command);
    let output = command
        .args(args)
        .args(["--download-host", &format!("http://{}", server.address())])
        .args(["--client-timeout", "1", "--skip-update-check"])
        .args(["--telemetry-disabled", "--format", "json"])
        .env("NO_COLOR", "1")
        // binstall reads this directly, and it would move the global root.
        .env_remove("APOLLO_NODE_MODULES_BIN_DIR")
        .env_remove("APOLLO_ROVER_NO_DOWNLOAD")
        .env_remove("APOLLO_ROVER_GLOBAL")
        .envs(env.iter().copied())
        .output()
        .unwrap();
    let stderr = String::from_utf8_lossy(&output.stderr).to_string();
    let json = serde_json::from_slice(&output.stdout)
        .unwrap_or_else(|err| panic!("stdout isn't JSON ({err})\nstderr: {stderr}"));
    (output.status.code(), json)
}

/// What `data.plugins` reports for `supergraph` v2.9.3 downloaded into `at`.
fn downloaded(levels: &TwoLevels, at: Level) -> Value {
    let level = match at {
        Level::Global => "global",
        Level::Project => "project",
    };
    let path = levels
        .bin_dir(at)
        .join(format!("supergraph-v2.9.3{}", std::env::consts::EXE_SUFFIX));
    json!([{
        "name": "supergraph",
        "version": "2.9.3",
        "source": "downloaded",
        "level": level,
        "path": path.as_str(),
    }])
}

fn lockfile(dir: &Utf8Path) -> Option<String> {
    fs::read_to_string(dir.join("plugin-versions.lock")).ok()
}

#[rstest]
fn a_project_in_scope_gets_the_plugin(mut two_levels: TwoLevels) {
    two_levels.run_from("packages/a");

    let (code, json) = rover(
        &two_levels,
        &["plugin", "install", "supergraph@=2.9.3"],
        &[],
    );

    assert_that!((code, &json["data"]["plugins"]))
        .named(&json.to_string())
        .is_equal_to((Some(0), &downloaded(&two_levels, Level::Project)));
    assert_that!(lockfile(&two_levels.project.rover_dir()))
        .is_equal_to(Some(format!("{HEADER}{LOCKED}")));
    // The global level is neither installed into nor recorded at.
    assert_that!((
        two_levels.global.bin_dir().exists(),
        lockfile(&two_levels.global.rover_dir()),
    ))
    .is_equal_to((false, None));
}

#[rstest]
fn with_no_project_the_plugin_installs_globally(two_levels: TwoLevels) {
    fs::remove_dir(two_levels.project.rover_dir()).unwrap();

    let (code, json) = rover(
        &two_levels,
        &["plugin", "install", "supergraph@=2.9.3"],
        &[],
    );

    assert_that!((code, &json["data"]["plugins"]))
        .named(&json.to_string())
        .is_equal_to((Some(0), &downloaded(&two_levels, Level::Global)));
    assert_that!(lockfile(&two_levels.global.rover_dir()))
        .is_equal_to(Some(format!("{HEADER}{LOCKED}")));
    // Nothing is invented in the working directory.
    assert_that!(two_levels.project.rover_dir().exists()).is_false();
}

#[rstest]
fn a_project_manifest_redirecting_its_install_root_stops_the_install(two_levels: TwoLevels) {
    let manifest = two_levels.project.rover_dir().join("rover.yaml");
    fs::write(&manifest, "install_root: ../vendor/rover\n").unwrap();

    let (code, json) = rover(
        &two_levels,
        &["plugin", "install", "supergraph@=2.9.3"],
        &[],
    );

    assert_that!((code, &json["error"]["code"]))
        .named(&json.to_string())
        .is_equal_to((Some(1), &Value::from("E052")));
    assert_that!((
        two_levels.project.bin_dir().exists(),
        two_levels.global.bin_dir().exists(),
    ))
    .is_equal_to((false, false));
}

#[rstest]
#[case::the_flag(&["--global"], &[])]
#[case::its_short_form(&["-g"], &[])]
#[case::the_variable(&[], &[("APOLLO_ROVER_GLOBAL", "true")])]
#[case::the_variable_as_one(&[], &[("APOLLO_ROVER_GLOBAL", "1")])]
fn global_installs_globally_inside_a_project(
    two_levels: TwoLevels,
    #[case] flags: &[&str],
    #[case] env: &[(&str, &str)],
) {
    let args: Vec<&str> = ["plugin", "install", "supergraph@=2.9.3"]
        .iter()
        .chain(flags)
        .copied()
        .collect();

    let (code, json) = rover(&two_levels, &args, env);

    assert_that!((code, &json["data"]["plugins"]))
        .named(&json.to_string())
        .is_equal_to((Some(0), &downloaded(&two_levels, Level::Global)));
    assert_that!(lockfile(&two_levels.global.rover_dir()))
        .is_equal_to(Some(format!("{HEADER}{LOCKED}")));
    // Nothing in the project changes.
    assert_that!(
        fs::read_dir(two_levels.project.rover_dir())
            .unwrap()
            .count()
    )
    .is_equal_to(0);
}

#[rstest]
fn a_variable_that_is_not_switched_on_leaves_the_project_default(two_levels: TwoLevels) {
    let (code, json) = rover(
        &two_levels,
        &["plugin", "install", "supergraph@=2.9.3"],
        &[("APOLLO_ROVER_GLOBAL", "false")],
    );

    assert_that!((code, &json["data"]["plugins"]))
        .named(&json.to_string())
        .is_equal_to((Some(0), &downloaded(&two_levels, Level::Project)));
}

#[rstest]
fn manifest_path_overrides_discovery(mut two_levels: TwoLevels) {
    let nested = two_levels.project.subdirectory("packages/b/.rover");
    two_levels.run_from("packages/b");
    let manifest = two_levels.project.rover_dir().join("rover.yaml");
    fs::write(&manifest, "plugins: {}\n").unwrap();

    let (code, json) = rover(
        &two_levels,
        &[
            "plugin",
            "install",
            "supergraph@=2.9.3",
            "-m",
            manifest.as_str(),
        ],
        &[],
    );

    assert_that!((code, &json["data"]["plugins"]))
        .named(&json.to_string())
        .is_equal_to((Some(0), &downloaded(&two_levels, Level::Project)));
    assert_that!(lockfile(&two_levels.project.rover_dir()))
        .is_equal_to(Some(format!("{HEADER}{LOCKED}")));
    // The project the working directory is in is ignored entirely.
    assert_that!(fs::read_dir(&nested).unwrap().count()).is_equal_to(0);
}

#[rstest]
fn manifest_path_with_global_is_refused_before_anything_happens(two_levels: TwoLevels) {
    let mut command = Command::new(cargo_bin("rover"));
    two_levels.apply(&mut command);
    let output = command
        .args(["plugin", "install", "supergraph@=2.9.3"])
        .args(["--manifest-path", ".rover/rover.yaml", "--global"])
        .env("NO_COLOR", "1")
        .output()
        .unwrap();

    // The usage line that follows lists whichever environment variables the
    // fixture set, so only the error itself is pinned.
    let stderr = String::from_utf8_lossy(&output.stderr).to_string();
    assert_that!((output.status.code(), stderr.lines().next())).is_equal_to((
        Some(2),
        Some("error: the argument '--manifest-path <FILE>' cannot be used with '--global'"),
    ));
    assert_that!(
        fs::read_dir(two_levels.project.rover_dir())
            .unwrap()
            .count()
    )
    .is_equal_to(0);
}

#[rstest]
fn manifest_path_with_the_global_variable_is_refused(two_levels: TwoLevels) {
    let (code, json) = rover(
        &two_levels,
        &[
            "plugin",
            "install",
            "supergraph@=2.9.3",
            "-m",
            ".rover/rover.yaml",
        ],
        &[("APOLLO_ROVER_GLOBAL", "true")],
    );

    assert_that!((code, &json["error"]["message"])).is_equal_to((
        Some(1),
        &Value::from(
            "`--manifest-path` names a project to install into, but `APOLLO_ROVER_GLOBAL` asks \
             for a global install.",
        ),
    ));
    assert_that!(
        fs::read_dir(two_levels.project.rover_dir())
            .unwrap()
            .count()
    )
    .is_equal_to(0);
    assert_that!(two_levels.global.bin_dir().exists()).is_false();
}
