//! `plugin-versions.lock` as the real binary writes it: every install records
//! what it installed, without disturbing what else is locked; a lockfile Rover
//! can't use stops an install before anything is downloaded; and a command
//! that installs a plugin on the fly never writes one.
//!
//! No command checks a lockfile against its manifest yet, so the drift tests
//! call that check directly, on a lockfile a real install wrote.

use std::fs;

use assert_cmd::Command;
use camino::Utf8Path;
use httpmock::{Method, MockServer};
use indoc::indoc;
use rover::plugin::lockfile::check_drift;
use rstest::rstest;
use serde_json::Value;
use speculoos::prelude::*;

use super::spellings::supergraph_tarball;
use crate::support::plugin_levels::{GlobalLevel, global_level};

const LOCKFILE: &str = "plugin-versions.lock";

const HEADER: &str = "# This file is generated by Rover. It is not intended for manual editing.\n";

/// A registry that resolves `latest-2` to v2.9.3 and serves that release's
/// `supergraph` artifact, holding `binary`.
struct Registry {
    server: MockServer,
    binary: Vec<u8>,
}

impl Registry {
    fn new(binary: &[u8]) -> Self {
        Self {
            server: MockServer::start(),
            binary: binary.to_vec(),
        }
    }

    fn host(&self) -> String {
        format!("http://{}", self.server.address())
    }

    /// Serve both requests, returning how many times the artifact was asked
    /// for once `run` is done with the registry.
    fn serve(&self, run: impl FnOnce(&str)) -> usize {
        self.server.mock(|when, then| {
            when.method(Method::HEAD).path_includes("/latest-2");
            then.status(302).header("X-Version", "v2.9.3");
        });
        let artifact = self.server.mock(|when, then| {
            // A floating request downloads from its alias's own URL.
            when.method(Method::GET).path_includes("/tar/supergraph/");
            then.status(200).body(supergraph_tarball(&self.binary));
        });
        run(&self.host());
        artifact.calls()
    }
}

/// Run `rover <args>` against `level` and a registry serving `supergraph`
/// v2.9.3, returning the exit code, the JSON envelope, and how many times the
/// artifact was downloaded.
fn rover(level: &GlobalLevel, args: &[&str]) -> (Option<i32>, Value, usize) {
    rover_with(level, args, &[])
}

/// [`rover`], with `env` set on the command too.
fn rover_with(
    level: &GlobalLevel,
    args: &[&str],
    env: &[(&str, &str)],
) -> (Option<i32>, Value, usize) {
    let registry = Registry::new(b"#!/bin/sh\n");
    let mut result = None;
    let downloads = registry.serve(|host| {
        let output = Command::cargo_bin("rover")
            .unwrap()
            .args(args)
            .args(["--download-host", host, "--client-timeout", "1"])
            .args(["--skip-update-check", "--telemetry-disabled"])
            .args(["--format", "json"])
            .envs(level.env())
            // binstall reads this directly, and it would move the install root.
            .env_remove("APOLLO_NODE_MODULES_BIN_DIR")
            .envs(env.iter().copied())
            .output()
            .unwrap();
        let stderr = String::from_utf8_lossy(&output.stderr).to_string();
        let json: Value = serde_json::from_slice(&output.stdout)
            .unwrap_or_else(|err| panic!("stdout isn't JSON ({err})\nstderr: {stderr}"));
        result = Some((output.status.code(), json));
    });
    let (code, json) = result.unwrap();
    (code, json, downloads)
}

fn lockfile(dir: &Utf8Path) -> Option<String> {
    fs::read_to_string(dir.join(LOCKFILE)).ok()
}

#[rstest]
#[case::an_exact_version(&["plugin", "install", "supergraph@=2.9.3"], "=2.9.3")]
#[case::a_floating_version(&["plugin", "install", "supergraph@2"], "2")]
#[case::the_deprecated_alias(&["install", "--plugin", "supergraph@=2.9.3"], "=2.9.3")]
fn an_install_records_what_it_asked_for_and_what_it_installed(
    global_level: GlobalLevel,
    #[case] args: &[&str],
    #[case] requested: &str,
) {
    let (code, json, downloads) = rover(&global_level, args);

    assert_that!((code, downloads))
        .named(&json.to_string())
        .is_equal_to((Some(0), 1));
    assert_that!(lockfile(&global_level.rover_dir())).is_equal_to(Some(format!(
        "{HEADER}version = 1\n\n[[plugins]]\nname = \"supergraph\"\nrequested = \"{requested}\"\n\
         resolved = \"2.9.3\"\n"
    )));
}

#[rstest]
fn installing_one_plugin_keeps_every_other_entry_as_it_was(global_level: GlobalLevel) {
    fs::write(
        global_level.rover_dir().join(LOCKFILE),
        indoc! {r#"
            version = 1

            [[plugins]]
            name = "supergraph"
            requested = "2"
            resolved = "2.9.0"

            [[plugins]]
            name = "router"
            requested = "latest"
            resolved = "2.1.0"
            checksum = "sha256:0a1b"
        "#},
    )
    .unwrap();

    let (code, _, _) = rover(&global_level, &["plugin", "install", "supergraph@=2.9.3"]);

    assert_that!(code).is_equal_to(Some(0));
    assert_that!(lockfile(&global_level.rover_dir())).is_equal_to(Some(format!(
        "{HEADER}{}",
        indoc! {r#"
            version = 1

            [[plugins]]
            name = "supergraph"
            requested = "=2.9.3"
            resolved = "2.9.3"

            [[plugins]]
            name = "router"
            requested = "latest"
            resolved = "2.1.0"
            checksum = "sha256:0a1b"
        "#}
    )));
}

#[rstest]
#[case::written_by_a_newer_rover("version = 2\nplugins = []\n")]
#[case::malformed("version = 1\nplugins = {}\n")]
fn a_lockfile_rover_cannot_use_stops_the_install_before_any_download(
    global_level: GlobalLevel,
    #[case] contents: &str,
) {
    fs::write(global_level.rover_dir().join(LOCKFILE), contents).unwrap();

    let (code, json, downloads) = rover(&global_level, &["plugin", "install", "supergraph@=2.9.3"]);

    assert_that!((code, &json["error"]["code"], downloads))
        .named(&json.to_string())
        .is_equal_to((Some(1), &Value::from("E052"), 0));
    assert_that!(lockfile(&global_level.rover_dir())).is_equal_to(Some(contents.to_string()));
    let binary = format!("supergraph-v2.9.3{}", std::env::consts::EXE_SUFFIX);
    assert_that!(global_level.bin_dir().join(binary).exists()).is_false();
}

/// An install into an npm package's `node_modules/.bin` is no level's, so it
/// neither records itself nor reads the global lockfile: one Rover can't use
/// there must not stop it.
#[rstest]
fn an_install_into_node_modules_leaves_the_global_lockfile_alone(global_level: GlobalLevel) {
    let unusable = "version = 2\n";
    fs::write(global_level.rover_dir().join(LOCKFILE), unusable).unwrap();
    let node_modules_bin = global_level.home().join("node_modules").join(".bin");
    fs::create_dir_all(&node_modules_bin).unwrap();

    let (code, json, downloads) = rover_with(
        &global_level,
        &["plugin", "install", "supergraph@=2.9.3"],
        &[("APOLLO_NODE_MODULES_BIN_DIR", node_modules_bin.as_str())],
    );

    assert_that!((code, downloads))
        .named(&json.to_string())
        .is_equal_to((Some(0), 1));
    let binary = format!("supergraph-v2.9.3{}", std::env::consts::EXE_SUFFIX);
    assert_that!(node_modules_bin.join(binary).exists()).is_true();
    assert_that!(lockfile(&global_level.rover_dir())).is_equal_to(Some(unusable.to_string()));
    assert_that!(lockfile(&node_modules_bin)).is_none();
}

/// Install, then declare `manifest` at the same level, and check the two.
fn drift_after_installing(level: &GlobalLevel, manifest: &str) -> Result<(), String> {
    let (code, _, _) = rover(level, &["plugin", "install", "supergraph@2"]);
    assert_that!(code).is_equal_to(Some(0));
    fs::write(level.rover_dir().join("rover.yaml"), manifest).unwrap();

    check_drift(&level.rover_dir()).map_err(|failure| failure.to_string())
}

#[rstest]
#[case::the_request_that_was_installed("plugins:\n  supergraph: \"2\"\n")]
#[case::the_release_that_was_installed("plugins:\n  supergraph: \"=2.9.3\"\n")]
#[case::latest("plugins:\n  supergraph: latest\n")]
fn a_manifest_declaring_what_was_installed_has_not_drifted(
    global_level: GlobalLevel,
    #[case] manifest: &str,
) {
    assert_that!(drift_after_installing(&global_level, manifest)).is_ok();
}

#[rstest]
#[case::another_exact_release(
    "plugins:\n  supergraph: \"=2.9.4\"\n",
    "`supergraph` is declared as `=2.9.4` but locked at `2.9.3`."
)]
#[case::a_major_the_installed_release_is_outside(
    "plugins:\n  supergraph: \"3\"\n",
    "`supergraph` is declared as `3` but locked at `2.9.3`."
)]
#[case::a_plugin_never_installed(
    "plugins:\n  supergraph: \"2\"\n  router: \"=2.1.0\"\n",
    "`router` is declared as `=2.1.0` but isn't locked."
)]
fn a_manifest_edited_after_an_install_has_drifted(
    global_level: GlobalLevel,
    #[case] manifest: &str,
    #[case] disagreement: &str,
) {
    let manifest_path = global_level.rover_dir().join("rover.yaml");

    assert_that!(drift_after_installing(&global_level, manifest)).is_equal_to(Err(format!(
        "The plugin lockfile is out of date with `{manifest_path}`: {disagreement}"
    )));
}

/// A command that downloads a plugin on the fly installs it just as `rover
/// plugin install` does, and must still never write a lockfile: not the one a
/// level already has, and not a new one where there was none. The plugin is a
/// shell script, so this is Unix-only.
#[cfg(unix)]
#[rstest]
#[case::levels_with_lockfiles(true)]
#[case::levels_without_lockfiles(false)]
fn a_plugin_downloaded_on_the_fly_is_never_recorded(#[case] with_lockfiles: bool) {
    use crate::support::plugin_levels::TwoLevels;

    let two_levels = TwoLevels::new();
    let global = two_levels.global.rover_dir();
    let project = two_levels.project.rover_dir();
    let locked = format!(
        "{HEADER}version = 1\n\n[[plugins]]\nname = \"router\"\nrequested = \"latest\"\nresolved = \"2.1.0\"\n"
    );
    if with_lockfiles {
        fs::write(global.join(LOCKFILE), &locked).unwrap();
        fs::write(project.join(LOCKFILE), &locked).unwrap();
    }
    fs::write(
        two_levels.working_dir().join("supergraph.yaml"),
        indoc! {r#"
            federation_version: "=2.9.3"
            subgraphs:
              users:
                routing_url: http://localhost:4002
                schema:
                  file: ./users.graphql
        "#},
    )
    .unwrap();
    fs::write(
        two_levels.working_dir().join("users.graphql"),
        "type Query { hello: String }\n",
    )
    .unwrap();
    let registry = Registry::new(
        b"#!/bin/sh\ncat <<'ROVER_TEST_PLUGIN_EOF'\n\
          {\"Ok\":{\"supergraphSdl\":\"type Query { hello: String }\",\"hints\":[]}}\n\
          ROVER_TEST_PLUGIN_EOF\n",
    );

    let mut status = None;
    let downloads = registry.serve(|host| {
        let mut command = std::process::Command::new(assert_cmd::cargo::cargo_bin("rover"));
        two_levels.apply(&mut command);
        let output = command
            .args(["supergraph", "compose", "--config", "supergraph.yaml"])
            .args(["--download-host", host, "--client-timeout", "1"])
            .args(["--skip-update-check", "--telemetry-disabled"])
            .env_remove("APOLLO_NODE_MODULES_BIN_DIR")
            .output()
            .unwrap();
        status = Some((
            output.status.code(),
            String::from_utf8_lossy(&output.stderr).to_string(),
        ));
    });
    let (code, stderr) = status.unwrap();

    assert_that!((code, downloads))
        .named(&stderr)
        .is_equal_to((Some(0), 1));
    let expected = with_lockfiles.then(|| locked.clone());
    assert_that!((lockfile(&global), lockfile(&project))).is_equal_to((expected.clone(), expected));
}
