//! The spec's acceptance criteria for a lockfile-driven install, through the
//! real binary: a committed lockfile installs the same release on every
//! machine without asking the registry to resolve anything, and installing
//! one plugin re-resolves only that plugin.

use std::{fs, process::Command};

use assert_cmd::cargo::cargo_bin;
use httpmock::{Method, MockServer};
use rstest::rstest;
use serde_json::{Value, json};
use speculoos::prelude::*;

use super::spellings::plugin_tarball;
use crate::support::plugin_levels::{TwoLevels, two_levels};

const LOCKFILE: &str = "plugin-versions.lock";

const HEADER: &str = "# This file is generated by Rover. It is not intended for manual editing.\n";

/// A registry with a newer release of each plugin than anything locked:
/// `supergraph` v2.9.5 and `router` v2.2.0. It serves every artifact with
/// `binary` inside.
struct Registry {
    binary: Vec<u8>,
}

/// What a run of Rover did: its exit code and JSON envelope, and how many
/// times it asked the registry to resolve each of `supergraph` and `router`.
type Run = (Option<i32>, Value, usize, usize);

impl Registry {
    fn new(binary: &[u8]) -> Self {
        Self {
            binary: binary.to_vec(),
        }
    }

    /// Run `rover <args>` at `levels` against this registry, counting only
    /// this run's requests.
    fn rover(&self, levels: &TwoLevels, args: &[&str]) -> Run {
        let server = MockServer::start();
        let resolutions = |plugin: &str, newest: &str| {
            server.mock(|when, then| {
                when.method(Method::HEAD)
                    .path_includes(format!("/{plugin}/"));
                then.status(302).header("X-Version", newest);
            })
        };
        let supergraph = resolutions("supergraph", "v2.9.5");
        let router = resolutions("router", "v2.2.0");
        for plugin in ["supergraph", "router"] {
            server.mock(|when, then| {
                when.method(Method::GET)
                    .path_includes(format!("/tar/{plugin}/"));
                then.status(200).body(plugin_tarball(plugin, &self.binary));
            });
        }

        let mut command = Command::new(cargo_bin("rover"));
        levels.apply(&mut command);
        let output = command
            .args(args)
            .args(["--download-host", &format!("http://{}", server.address())])
            .args(["--client-timeout", "1", "--skip-update-check"])
            .args(["--telemetry-disabled", "--format", "json"])
            .env("NO_COLOR", "1")
            // binstall reads this directly, and it would move the global root.
            .env_remove("APOLLO_NODE_MODULES_BIN_DIR")
            .env_remove("APOLLO_ROVER_NO_DOWNLOAD")
            .env_remove("APOLLO_ROVER_SKIP_UPDATE")
            .env_remove("APOLLO_ROVER_GLOBAL")
            .output()
            .unwrap();
        let stderr = String::from_utf8_lossy(&output.stderr).to_string();
        let json = serde_json::from_slice(&output.stdout)
            .unwrap_or_else(|err| panic!("stdout isn't JSON ({err})\nstderr: {stderr}"));
        (
            output.status.code(),
            json,
            supergraph.calls(),
            router.calls(),
        )
    }
}

/// `plugin` at `version` as `data.plugins` reports it, in the project of
/// `levels`.
fn reported(levels: &TwoLevels, plugin: &str, version: &str, source: &str) -> Value {
    let path = levels.project.bin_dir().join(format!(
        "{plugin}-v{version}{}",
        std::env::consts::EXE_SUFFIX
    ));
    json!({
        "name": plugin,
        "version": version,
        "source": source,
        "level": "project",
        "path": path.as_str(),
    })
}

/// Given a project with a committed `rover.yaml` declaring `supergraph: "2"`
/// and a `plugin-versions.lock` recording `2.9.3`, when `rover plugin
/// install` runs on two clean machines, then both install exactly `2.9.3`
/// into their project roots, neither makes a resolution request to the
/// registry, and `rover supergraph compose --format json` on both reports
/// `"version": "2.9.3"`.
///
/// Composing runs the installed plugin, a shell script, so this is Unix-only.
#[cfg(unix)]
#[test]
fn a_committed_lockfile_installs_the_same_release_on_two_clean_machines() {
    let lockfile = format!(
        "{HEADER}version = 1\n\n[[plugins]]\nname = \"supergraph\"\nrequested = \"2\"\n\
         resolved = \"2.9.3\"\n"
    );
    let registry = Registry::new(
        b"#!/bin/sh\ncat <<'ROVER_TEST_PLUGIN_EOF'\n\
          {\"Ok\":{\"supergraphSdl\":\"type Query { hello: String }\",\"hints\":[]}}\n\
          ROVER_TEST_PLUGIN_EOF\n",
    );

    for _machine in 0..2 {
        // A fresh checkout of the committed project, on a machine with
        // nothing installed at either level.
        let levels = TwoLevels::new();
        let committed = levels.project.rover_dir();
        fs::write(
            committed.join("rover.yaml"),
            "plugins:\n  supergraph: \"2\"\n",
        )
        .unwrap();
        fs::write(committed.join(LOCKFILE), &lockfile).unwrap();
        fs::write(
            levels.working_dir().join("supergraph.yaml"),
            "subgraphs:\n  users:\n    routing_url: http://localhost:4002\n    schema:\n      \
             file: ./users.graphql\n",
        )
        .unwrap();
        fs::write(
            levels.working_dir().join("users.graphql"),
            "type Query { hello: String }\n",
        )
        .unwrap();

        let (code, json, supergraph, router) = registry.rover(&levels, &["plugin", "install"]);
        assert_that!((code, &json["data"]["plugins"], supergraph, router))
            .named(&json.to_string())
            .is_equal_to((
                Some(0),
                &json!([reported(&levels, "supergraph", "2.9.3", "downloaded")]),
                0,
                0,
            ));

        let compose = ["supergraph", "compose", "--config", "supergraph.yaml"];
        let (code, json, supergraph, router) = registry.rover(&levels, &compose);
        assert_that!((code, &json["data"]["plugins"], supergraph, router))
            .named(&json.to_string())
            .is_equal_to((
                Some(0),
                &json!([reported(&levels, "supergraph", "2.9.3", "installed")]),
                0,
                0,
            ));
        assert_that!(fs::read_to_string(committed.join(LOCKFILE)).unwrap())
            .is_equal_to(lockfile.clone());
        // Nothing is installed globally, though looking may make the directory.
        let global = fs::read_dir(levels.global.bin_dir())
            .into_iter()
            .flatten()
            .count();
        assert_that!(global).is_equal_to(0);
    }
}

/// Given a project lockfile recording `supergraph: 2.9.3` (requested `2`) and
/// `router: 2.1.0` (requested `latest`), and newer releases of both
/// available, when `rover plugin install router@latest` runs, then `router`
/// is re-resolved and updated and `supergraph`'s locked `2.9.3` is untouched.
/// A bare install afterwards re-resolves neither.
#[rstest]
fn installing_one_plugin_does_not_re_resolve_the_others(two_levels: TwoLevels) {
    let lock = two_levels.project.rover_dir().join(LOCKFILE);
    let supergraph_entry =
        "[[plugins]]\nname = \"supergraph\"\nrequested = \"2\"\nresolved = \"2.9.3\"\n";
    fs::write(
        &lock,
        format!(
            "{HEADER}version = 1\n\n{supergraph_entry}\n[[plugins]]\nname = \"router\"\n\
             requested = \"latest\"\nresolved = \"2.1.0\"\n"
        ),
    )
    .unwrap();
    let registry = Registry::new(b"#!/bin/sh\n");

    let (code, json, supergraph, router) =
        registry.rover(&two_levels, &["plugin", "install", "router@latest"]);

    assert_that!((code, &json["data"]["plugins"], supergraph, router))
        .named(&json.to_string())
        .is_equal_to((
            Some(0),
            &json!([reported(&two_levels, "router", "2.2.0", "downloaded")]),
            0,
            1,
        ));
    // `router@latest` asks for the newest 2.x, which is how it's recorded.
    let updated = format!(
        "{HEADER}version = 1\n\n{supergraph_entry}\n[[plugins]]\nname = \"router\"\n\
         requested = \"2\"\nresolved = \"2.2.0\"\n"
    );
    assert_that!(fs::read_to_string(&lock).unwrap()).is_equal_to(updated.clone());

    let (code, json, supergraph, router) = registry.rover(&two_levels, &["plugin", "install"]);

    assert_that!((code, &json["data"]["plugins"], supergraph, router))
        .named(&json.to_string())
        .is_equal_to((
            Some(0),
            &json!([
                reported(&two_levels, "supergraph", "2.9.3", "downloaded"),
                reported(&two_levels, "router", "2.2.0", "installed"),
            ]),
            0,
            0,
        ));
    assert_that!(fs::read_to_string(&lock).unwrap()).is_equal_to(updated);
}
