[package]
name = "graphql-schema"
version = "0.1.0"
authors = ["lrlna <shestak.irina@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
