[package]
authors = ["lrlna <shestak.irina@gmail.com>"]
edition = "2018"
name = "graphql-schema"
version = "0.1.0"

[dependencies]
graphql-parser = "^0.2"
heck = "0.3"
introspection = {path = "../introspection"}
serde_json = "1"
thiserror = "1.0.10"
