[package]
name = "rover-error"
version = "0.1.0"
authors = ["Avery Harnish <avery@apollographql.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
reqwest = "0.11"
serde_json = "1.0"
