on:
  pull_request:
    paths:
      - "**/*.md"
  schedule:
    - cron: '0 0 * * *'

permissions: {}

name: Check Markdown Links
jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - uses: jdx/mise-action@dba19683ed58901619b14f395a24841710cb4925 # v4.1.0
      - run: mise run check-links
