on:
  workflow_dispatch:
    inputs:
      composition-versions:
        description: 'JSON list of supergraph versions'
        required: true
        type: string
      router-versions:
        description: 'JSON list of router versions'
        required: true
        type: string
      dev-next:
        description: 'Compile binaries with the dev-next flag'
        type: boolean

name: "Run Smoke Tests (Manually)"
jobs:
  run-smokes:
    uses: ./.github/workflows/smoke-test.yml
    with:
      composition-versions: ${{ inputs.composition-versions }}
      router-versions: ${{ inputs.router-versions }}
      dev-next: ${{ inputs.dev-next }}
    secrets: inherit
