on:
  workflow_dispatch:
    inputs:
      composition-versions:
        description: 'JSON list of supergraph versions'
        required: true
        type: string
      router-versions:
        description: 'JSON list of router versions'
        required: true
        type: string

name: "Run Smoke Tests (Manually)"
jobs:
  run-smokes:
    uses: ./.github/workflows/smoke-test.yml
    with:
      composition-versions: ${{ inputs.composition-versions }}
      router-versions: ${{ inputs.router-versions }}
    secrets: inherit